name: Infra & CD

on:
  push:
    branches: [ main ]

jobs:
  terraform:
    name: Terraform
    runs-on: ubuntu-latest
    outputs:
      ecr_uri: ${{ steps.get_ecr.outputs.registry }}
    steps:
      - uses: actions/checkout@v4

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id:     ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region:            ${{ secrets.AWS_REGION }}

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2

      # ── NEW: Initialize Terraform ──────────────────────────────────────
      - name: Terraform Init
        run: terraform init

      # ── NEW: Import pending-deletion secrets into state ───────────────
      - name: Import existing secrets into state
        run: |
          terraform import aws_secretsmanager_secret.openai  arn:aws:secretsmanager:${{ secrets.AWS_REGION }}:${{ secrets.AWS_ACCOUNT_ID }}:secret:openai/daily-video-renderer
          terraform import aws_secretsmanager_secret.youtube arn:aws:secretsmanager:${{ secrets.AWS_REGION }}:${{ secrets.AWS_ACCOUNT_ID }}:secret:prod/YouTubeUploader/credentials

      # ── NEW: Destroy just those two secrets ────────────────────────────
      - name: Destroy old secrets
        run: |
          terraform destroy \
            -target=aws_secretsmanager_secret.openai \
            -target=aws_secretsmanager_secret.youtube \
            -auto-approve

      # ── Package Lambda ZIP ────────────────────────────────────────────
      - name: Package Lambda
        run: |
          zip youtube-uploader-deployment.zip lambda_function.py

      # ── Full apply to recreate secrets + all infra ────────────────────
      - name: Terraform Apply
        id: tf_apply
        run: |
          terraform apply -auto-approve \
            -var="account_id=${{ secrets.AWS_ACCOUNT_ID }}" \
            -var="openai_api_key=${{ secrets.OPENAI_API_KEY }}" \
            -var="youtube_client_id=${{ secrets.YOUTUBE_CLIENT_ID }}" \
            -var="youtube_client_secret=${{ secrets.YOUTUBE_CLIENT_SECRET }}" \
            -var="youtube_refresh_token=${{ secrets.YOUTUBE_REFRESH_TOKEN }}" \
            -var="lambda_zip_path=youtube-uploader-deployment.zip"

      - name: Get ECR URI
        id: get_ecr
        run: |
          echo "registry=$(aws ecr describe-repositories \
            --repository-names daily-video-renderer \
            --query 'repositories[0].repositoryUri' \
            --output text)" >> $GITHUB_OUTPUT

  build_and_push:
    name: Build & Push Docker
    needs: terraform
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id:     ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region:            ${{ secrets.AWS_REGION }}

      - name: Login to ECR
        run: |
          aws ecr get-login-password --region ${{ secrets.AWS_REGION }} |
            docker login --username AWS --password-stdin ${{ needs.terraform.outputs.ecr_uri }}

      - name: Build & Tag Image
        run: |
          docker build -t ${{ needs.terraform.outputs.ecr_uri }}:latest .
          docker tag ${{ needs.terraform.outputs.ecr_uri }}:latest ${{ needs.terraform.outputs.ecr_uri }}:latest

      - name: Push to ECR
        run: |
          docker push ${{ needs.terraform.outputs.ecr_uri }}:latest