name: Infra & CD

on:
  push:
    branches: [ main ]

jobs:
  terraform_apply:
    name: Terraform & Secrets
    runs-on: ubuntu-latest
    outputs:
      ecr_uri: ${{ steps.get_ecr.outputs.registry }}
    steps:
      - name: Check out code
        uses: actions/checkout@v4

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id:     ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region:            ${{ secrets.AWS_REGION }}

      - name: Restore Secrets (if pending deletion)
        run: |
          aws secretsmanager restore-secret \
            --secret-id openai/daily-video-renderer \
            --region ${{ secrets.AWS_REGION }} || echo "openai secret not pending"
          aws secretsmanager restore-secret \
            --secret-id prod/YouTubeUploader/credentials \
            --region ${{ secrets.AWS_REGION }} || echo "youtube secret not pending"

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2

      - name: Package Lambda
        run: |
          zip youtube-uploader-deployment.zip lambda_function.py

      - name: Terraform Init & Apply
        id: tf_apply
        run: |
          terraform init
          terraform apply -auto-approve \
            -var="account_id=${{ secrets.AWS_ACCOUNT_ID }}" \
            -var="openai_api_key=${{ secrets.OPENAI_API_KEY }}" \
            -var="youtube_client_id=${{ secrets.YOUTUBE_CLIENT_ID }}" \
            -var="youtube_client_secret=${{ secrets.YOUTUBE_CLIENT_SECRET }}" \
            -var="youtube_refresh_token=${{ secrets.YOUTUBE_REFRESH_TOKEN }}" \
            -var="lambda_zip_path=youtube-uploader-deployment.zip"
        env:
          AWS_ACCOUNT_ID:    ${{ secrets.AWS_ACCOUNT_ID }}
          OPENAI_API_KEY:    ${{ secrets.OPENAI_API_KEY }}
          YOUTUBE_CLIENT_ID: ${{ secrets.YOUTUBE_CLIENT_ID }}
          YOUTUBE_CLIENT_SECRET: ${{ secrets.YOUTUBE_CLIENT_SECRET }}
          YOUTUBE_REFRESH_TOKEN: ${{ secrets.YOUTUBE_REFRESH_TOKEN }}

      - name: Get ECR repository URI
        id: get_ecr
        run: |
          echo "registry=$(aws ecr describe-repositories \
            --repository-names daily-video-renderer \
            --query 'repositories[0].repositoryUri' \
            --output text)" >> $GITHUB_OUTPUT

  build_and_push:
    name: Build & Push Docker Image
    needs: terraform_apply
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v4

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id:     ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region:            ${{ secrets.AWS_REGION }}

      - name: Login to ECR
        run: |
          aws ecr get-login-password --region ${{ secrets.AWS_REGION }} \
          | docker login --username AWS --password-stdin ${{ needs.terraform_apply.outputs.ecr_uri }}

      - name: Build Docker image
        run: |
          docker build -t ${{ needs.terraform_apply.outputs.ecr_uri }}:latest .

      - name: Push to ECR
        run: |
          docker push ${{ needs.terraform_apply.outputs.ecr_uri }}:latest